version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: uber-popug-employee-billing-postgres
    ports:
      - '5430:5432'
    environment:
      POSTGRES_DB: 'db_uber_popug_employee_billing'
      POSTGRES_USER: 'dbusername'
      POSTGRES_PASSWORD: 'dbpassword'
    labels:
      org.springframework.boot.ignore: true
