version: "3.8"

services:
  postgres:
    image: postgres:16.2
    container_name: uber-popug-auth-service-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dbusername}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dbpassword}
      POSTGRES_DB: db_uber_popug_auth_service
    ports:
      - "5431:5431"
    restart: unless-stopped
    networks:
      - uber-popug-auth-keycloak-network

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: uber-popug-auth-service-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: uber-popug-auth-service-postgres
      DB_DATABASE: db_uber_popug_auth_service
      DB_USER: ${POSTGRES_USER:-dbusername}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-dbpassword}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    networks:
      - uber-popug-auth-keycloak-network

networks:
  uber-popug-auth-keycloak-network:
    driver: bridge
